CREATE TABLE employees ( 
	idnumber INT NOT NULL PRIMARY KEY, 
	firstName VARCHAR(30) NOT NULL, 
	lastName VARCHAR(30) NOT NULL, 
	email VARCHAR(50), start_date 
	TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
	);